#!/usr/bin/env bash
set -euo pipefail

repo_root="$(cd "$(dirname "$0")/.." && pwd)"
source "$repo_root/script/require_macos_build_prereqs.sh"

require_macos_build_prereqs

generated_runtime_dir="$repo_root/app/Sources/Generated"
generated_runtime_file="$generated_runtime_dir/BrokerRuntimeVersion.generated.swift"
generated_app_metadata_dir="$repo_root/app/Generated"
generated_app_metadata_file="$generated_app_metadata_dir/SimulatorBrokerApp-Info.plist"
mkdir -p "$generated_runtime_dir"
mkdir -p "$generated_app_metadata_dir"
generated_runtime_temp="$(mktemp "$generated_runtime_dir/.BrokerRuntimeVersion.generated.swift.XXXXXX")"
generated_app_metadata_temp="$(mktemp "$generated_app_metadata_dir/.SimulatorBrokerApp-Info.plist.XXXXXX")"

cleanup_generated_runtime() {
  rm -f "$generated_runtime_temp" "$generated_app_metadata_temp"
}
trap cleanup_generated_runtime EXIT

node --input-type=module - \
  "$repo_root/package.json" \
  "$generated_runtime_temp" \
  "$generated_app_metadata_temp" <<'NODE'
import fs from "node:fs";

const [, , packagePath, swiftOutputPath, appMetadataOutputPath] = process.argv;
const packageMetadata = JSON.parse(fs.readFileSync(packagePath, "utf8"));
const runtimeVersion = packageMetadata.version;
if (typeof runtimeVersion !== "string" || !/^[0-9A-Za-z.+-]+$/.test(runtimeVersion)) {
  throw new Error("package.json version must be a non-empty package version string.");
}

fs.writeFileSync(
  swiftOutputPath,
  `// Generated by scripts/generate_app_project.sh. Do not edit.\n`+
    `enum BrokerRuntimeBuildVersion {\n`+
    `  static let current = ${JSON.stringify(runtimeVersion)}\n`+
    `}\n`,
);
fs.writeFileSync(
  appMetadataOutputPath,
  `<?xml version="1.0" encoding="UTF-8"?>\n`+
    `<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">\n`+
    `<plist version="1.0">\n`+
    `<dict>\n`+
    `  <key>CFBundleDevelopmentRegion</key>\n`+
    `  <string>$(DEVELOPMENT_LANGUAGE)</string>\n`+
    `  <key>CFBundleDisplayName</key>\n`+
    `  <string>Simulator Broker</string>\n`+
    `  <key>CFBundleExecutable</key>\n`+
    `  <string>$(EXECUTABLE_NAME)</string>\n`+
    `  <key>CFBundleIdentifier</key>\n`+
    `  <string>$(PRODUCT_BUNDLE_IDENTIFIER)</string>\n`+
    `  <key>CFBundleInfoDictionaryVersion</key>\n`+
    `  <string>6.0</string>\n`+
    `  <key>CFBundleName</key>\n`+
    `  <string>$(PRODUCT_NAME)</string>\n`+
    `  <key>CFBundlePackageType</key>\n`+
    `  <string>APPL</string>\n`+
    `  <key>CFBundleShortVersionString</key>\n`+
    `  <string>${runtimeVersion}</string>\n`+
    `  <key>CFBundleVersion</key>\n`+
    `  <string>${runtimeVersion}</string>\n`+
    `  <key>LSApplicationCategoryType</key>\n`+
    `  <string>public.app-category.developer-tools</string>\n`+
    `  <key>SimulatorBrokerExpectedRuntimeVersion</key>\n`+
    `  <string>${runtimeVersion}</string>\n`+
    `</dict>\n`+
    `</plist>\n`,
);
NODE
chmod 0644 "$generated_runtime_temp"
chmod 0644 "$generated_app_metadata_temp"
mv -f "$generated_runtime_temp" "$generated_runtime_file"
mv -f "$generated_app_metadata_temp" "$generated_app_metadata_file"
trap - EXIT

xcodegen generate --spec "$repo_root/app/project.yml"
