#!/usr/bin/env bash
set -euo pipefail

repo_root="$(cd "$(dirname "$0")/.." && pwd)"
source "$repo_root/script/require_macos_build_prereqs.sh"

require_macos_build_prereqs

generated_runtime_dir="$repo_root/app/Sources/Generated"
generated_runtime_file="$generated_runtime_dir/BrokerRuntimeVersion.generated.swift"
mkdir -p "$generated_runtime_dir"
generated_runtime_temp="$(mktemp "$generated_runtime_dir/.BrokerRuntimeVersion.generated.swift.XXXXXX")"

cleanup_generated_runtime() {
  rm -f "$generated_runtime_temp"
}
trap cleanup_generated_runtime EXIT

node --input-type=module - "$repo_root/package.json" "$generated_runtime_temp" <<'NODE'
import fs from "node:fs";

const [, , packagePath, outputPath] = process.argv;
const packageMetadata = JSON.parse(fs.readFileSync(packagePath, "utf8"));
const runtimeVersion = packageMetadata.version;
if (typeof runtimeVersion !== "string" || !/^[0-9A-Za-z.+-]+$/.test(runtimeVersion)) {
  throw new Error("package.json version must be a non-empty package version string.");
}

fs.writeFileSync(
  outputPath,
  `// Generated by scripts/generate_app_project.sh. Do not edit.\n`+
    `enum BrokerRuntimeBuildVersion {\n`+
    `  static let current = ${JSON.stringify(runtimeVersion)}\n`+
    `}\n`,
);
NODE
chmod 0644 "$generated_runtime_temp"
mv -f "$generated_runtime_temp" "$generated_runtime_file"
trap - EXIT

xcodegen generate --spec "$repo_root/app/project.yml"
